# Generated by Django 2.2.6 on 2019-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='related',
            field=models.ManyToManyField(related_name='_personality_related_+', to='mentor_finder.Personality'),
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='goals',
        ),
        migrations.AddField(
            model_name='mentee',
            name='goals',
            field=models.ManyToManyField(to='mentor_finder.Goal', verbose_name='Goals'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='title',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
