# Generated by Django 2.2.6 on 2019-10-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_finder', '0002_goal_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='name',
        ),
    ]
