# Generated by Django 2.2.6 on 2019-10-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_finder', '0003_remove_siteuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='mentor_finder.Task'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='headline',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='mentor_finder.Message'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='photo_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
